services:
  db:
    image: postgres:16
    container_name: fantasy-oscars-db
    environment:
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy
      POSTGRES_DB: fantasy_oscars
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
